#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: ikghxpwqbt

on:
  push:
    branches: 
      - master

jobs:

  build_openwrt:

    name: 树莓派4B

    runs-on: ubuntu-20.04

    steps:
      - name: 校验本地文件
        uses: actions/checkout@main

      - name: 初始化系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get update
          sudo -E apt-get -y dist-upgrade
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "Asia/Hong Kong"

      - name: 克隆源码
        run: |
          git clone -b openwrt-21.02 --single-branch https://github.com/ikghx/openwrt-life openwrt
          mv ./openwrt/* ./

      - name: 更新feeds源
        run: |
          ./scripts/feeds update -a

      - name: 删除部分packages文件
        run: |
          pushd feeds/packages/net
          rm -rf adguardhome
          rm -rf brook
          rm -rf chinadns-ng
          rm -rf dns2socks
          rm -rf dns2tcp
          rm -rf dnsproxy
          rm -rf hysteria
          rm -rf ipt2socks
          rm -rf microsocks
          rm -rf naiveproxy
          rm -rf pdnsd-alt
          rm -rf shadowsocks-rust
          rm -rf shadowsocksr-libev
          rm -rf simple-obfs
          rm -rf smartdns
          rm -rf ssocks
          rm -rf tcping
          rm -rf trojan
          rm -rf trojan-go
          rm -rf trojan-plus
          rm -rf v2ray-core
          rm -rf v2ray-geodata
          rm -rf v2ray-plugin
          rm -rf xray-core
          rm -rf xray-plugin

      - name: 删除部分luci文件
        run: |
          pushd feeds/luci/applications
          rm -rf luci-app-fileassistant
          rm -rf luci-app-passwall

      - name: 安装feeds源
        run: |
          ./scripts/feeds install -a

      - name: Timezone patch
        run: |
          patch -p1 < patches/Patch-RPI-4.patch

      - name: 构建自定义文件结构
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/symonlee/openwrt-smartdns xipk
          pushd xipk
          rm -rf AdGuardHome
          popd
          svn co https://github.com/kiddin9/openwrt-packages/trunk/luci-app-fileassistant
          svn co https://github.com/Lienol/openwrt-package/branches/other/lean/ipv6-helper
          svn co https://github.com/kiddin9/openwrt-packages/trunk/luci-app-qbittorrent-simple
          git clone https://github.com/xiaorouji/openwrt-passwall
          git clone -b luci --single-branch https://github.com/xiaorouji/openwrt-passwall luci-app-passwall
          pushd luci-app-passwall/luci-app-passwall/root/etc
          rm -rf hotplug.d

      - name: 载入自定义配置
        run: |
          sed -i 's/%D %V %C/OpenWrt 21.02-SNAPSHOT 21.02/g' package/base-files/files/etc/openwrt_release
          sed -i '6,$d' package/base-files/files/etc/banner
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF

          # 编译rpi-4固件:
          CONFIG_TARGET_bcm27xx=y
          CONFIG_TARGET_bcm27xx_bcm2711=y
          CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y

          # 编译ext4固件:
          CONFIG_TARGET_ROOTFS_EXT4FS=y
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set

          # 设置固件大小:
          CONFIG_TARGET_ROOTFS_PARTSIZE=1984

          # IPv6支持:
          # CONFIG_PACKAGE_dnsmasq is not set
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_ip6tables-mod-nat=y
          CONFIG_PACKAGE_ipv6helper=y

          # 文件系统支持:
          CONFIG_PACKAGE_block-mount=y

          # 去掉板载无线:
          # CONFIG_PACKAGE_cypress-firmware-43455-sdio is not set
          # CONFIG_PACKAGE_cypress-nvram-43455-sdio-rpi-4b is not set
          # CONFIG_PACKAGE_kmod-brcmfmac is not set

          # USB3.0支持:
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y

          # 系统中文支持:
          CONFIG_LUCI_LANG_zh_Hans=y

          # 常用LuCI插件选择:
          CONFIG_PACKAGE_luci-app-fileassistant=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-app-passwall=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Geodata=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-samba4=y
          CONFIG_PACKAGE_luci-app-sqm=y

          # 常用软件包:
          CONFIG_PACKAGE_AdGuardHome=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_dnsproxy=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          # CONFIG_PACKAGE_wpad-basic-wolfssl is not set
          # CONFIG_XRAY_CORE_COMPRESS_UPX is not set
          
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: 下载软件包
        run: make download -j16

      - name: 进行固件编译
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: 固件整理
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
