#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: 🏕21.02samba4

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 6 * * 3

jobs:

  build_openwrt:

    name: 树莓派4B

    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: 校验本地文件
        uses: actions/checkout@main

      - name: 初始化系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install build-essential cmake asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python2.7 python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf intltool mkisofs rsync
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get -qq clean

      - name: 克隆源码
        run: |
          git clone -b openwrt-21.02 --single-branch https://github.com/immortalwrt/immortalwrt
          mv ./immortalwrt/* ./

      - name: 更新安装feeds源
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 删除部分安装文件
        run: |
          pushd feeds/packages/net
          rm -rf adguardhome
          rm -rf smartdns

      - name: 删除部分luci文件
        run: |
          pushd feeds/luci/applications
          rm -rf luci-app-adguardhome

      - name: 构建自定义文件结构
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/symonlee/luci-app-adguardhome
          git clone https://github.com/symonlee/openwrt-smartdns
          git clone https://github.com/symonlee/pd-adg-smartdns-le-etc

      - name: 删除部自定义文件
        run: |
          pushd package/openwrt-packages/pd-adg-smartdns-le-etc
          rm -rf autosamba
          rm -rf smartdns

      - name: 载入自定义配置
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF

          # 编译rpi-4固件:
          CONFIG_TARGET_bcm27xx=y
          CONFIG_TARGET_bcm27xx_bcm2711=y
          CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y

          # 编译ext4固件:
          CONFIG_TARGET_ROOTFS_EXT4FS=y
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set

          # 设置固件大小:
          CONFIG_TARGET_ROOTFS_PARTSIZE=1984

          # IPv6支持:
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y

          # 硬盘自动挂载:
          CONFIG_PACKAGE_automount=y
          CONFIG_PACKAGE_autosamba=y

          # 去掉板载无线:
          # CONFIG_PACKAGE_cypress-firmware-43455-sdio is not set
          # CONFIG_PACKAGE_cypress-nvram-43455-sdio-rpi-4b is not set
          # CONFIG_PACKAGE_kmod-brcmfmac is not set

          # USB3.0支持:
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y

          # 系统中文支持:
          CONFIG_DEFAULT_SETTINGS_OPTIMIZE_FOR_CHINESE=y

          # 常用LuCI插件选择:
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-aria2=y
          # CONFIG_PACKAGE_luci-app-arpbind is not set
          CONFIG_PACKAGE_luci-app-autoreboot=y
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-filetransfer is not set
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-transmission=y
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          # CONFIG_PACKAGE_luci-app-wol is not set

          # 常用软件包:
          CONFIG_PACKAGE_AdGuardHome=y
          # CONFIG_XRAY_CORE_COMPRESS_UPX is not set
          
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: 下载软件包
        run: |
          make download -j8 || make download -j1 V=s
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 进行固件编译
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "::set-output name=status::success"

      - name: 固件整理
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 8
          keep_minimum_runs: 3
