#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: officialpw

on:
  push:
    branches: 
      - master

jobs:

  build_openwrt:

    name: 树莓派4B

    runs-on: ubuntu-latest

    steps:
      - name: 初始化系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Hong_Kong"

      - name: 校验本地文件
        uses: actions/checkout@main

      - name: 克隆源码
        run: |
          git clone -b 22.03 --single-branch https://github.com/Lienol/openwrt openwrt
          mv ./openwrt/* ./

      - name: 更新feeds源
        run: |
          ./scripts/feeds update -a

      - name: 删除部分packages文件
        run: |
          pushd feeds/packages/net
          rm -rf adguardhome
          rm -rf dnsproxy
          rm -rf microsocks
          rm -rf sing-box
          rm -rf smartdns
          rm -rf trojan-go
          rm -rf v2ray-core
          rm -rf v2ray-geodata
          rm -rf xray-core

      - name: 删除部分other文件
        run: |
          pushd feeds/other/lean
          rm -rf luci-app-qbittorrent
          rm -rf qBittorrent-static
          rm -rf qBittorrent
          rm -rf qtbase
          rm -rf qttools
          rm -rf rblibtorrent

      - name: 安装feeds源
        run: |
          ./scripts/feeds install -a

      - name: 构建自定义文件结构
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/symonlee/openwrt-smartdns xipk
          pushd xipk
          rm -rf AdGuardHome
          popd
          git clone https://github.com/sbwml/openwrt-qBittorrent
          pushd openwrt-qBittorrent
          rm -rf qBittorrent-static
          rm -rf qBittorrent
          popd
          git clone https://github.com/xiaorouji/openwrt-passwall luci-app-passwall
          git clone https://github.com/xiaorouji/openwrt-passwall-packages
          pushd luci-app-passwall/luci-app-passwall/root/etc
          rm -rf hotplug.d

      - name: 载入自定义配置
        run: |
          sed -i '8s/1/0/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '9s/dns2tcp/udp/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '10s/1.1.1.1/127.0.0.1:5335/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '12,13d' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '18s/proxy/disable/2' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '20s/1/0/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '22,23s/1/0/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '92,104d' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i 's/+chinadns-ng +dns2socks/+dns2socks/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/Makefile
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF

          # 编译rpi-4固件:
          CONFIG_TARGET_bcm27xx=y
          CONFIG_TARGET_bcm27xx_bcm2711=y
          CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y

          # 编译ext4固件:
          CONFIG_TARGET_ROOTFS_EXT4FS=y
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set

          # 设置固件大小:
          CONFIG_TARGET_ROOTFS_PARTSIZE=1984

          # 文件系统支持:
          CONFIG_PACKAGE_autocore-arm=y
          CONFIG_PACKAGE_automount=y
          CONFIG_PACKAGE_ipv6helper=y

          # 去掉板载无线:
          # CONFIG_PACKAGE_cypress-firmware-43455-sdio is not set
          # CONFIG_PACKAGE_cypress-nvram-43455-sdio-rpi-4b is not set
          # CONFIG_PACKAGE_kmod-brcmfmac is not set

          # USB3.0支持:
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y

          # 常用LuCI插件选择:
          # CONFIG_PACKAGE_luci-app-control-timewol is not set
          # CONFIG_PACKAGE_luci-app-control-webrestriction is not set
          # CONFIG_PACKAGE_luci-app-control-weburl is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-ramfree is not set
          # CONFIG_PACKAGE_luci-app-timecontrol is not set
          # CONFIG_PACKAGE_luci-app-upnp is not set
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-ksmbd=y
          CONFIG_PACKAGE_luci-app-passwall=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Geodata is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray is not set
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-qbittorrent_static=y
          # CONFIG_PACKAGE_luci-app-qbittorrent_dynamic is not set
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-turboacc=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_BBR_CCA=y

          # 常用软件包:
          CONFIG_PACKAGE_AdGuardHome=y
          CONFIG_PACKAGE_dnsproxy=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_bind-dig=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          # CONFIG_PACKAGE_wpad-basic-mbedtls is not set
          # CONFIG_PACKAGE_wpad-basic-openssl is not set
          # CONFIG_PACKAGE_wpad-basic-wolfssl is not set
          
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: 进行固件编译
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: 固件整理
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
