#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: officialpw

on:
  push:
    branches: 
      - master

jobs:

  build_openwrt:

    name: NanoPi R6S

    runs-on: ubuntu-latest

    steps:
      - name: 初始化系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Hong_Kong"

      - name: 校验本地文件
        uses: actions/checkout@main

      - name: 克隆源码
        run: |
          git clone -b master --single-branch https://github.com/immortalwrt/immortalwrt openwrt
          mv ./openwrt/* ./

      - name: 修改部分patch文件
        run: |
          sed -i '29s/1/0/g' package/network/config/firewall4/patches/001-firewall4-add-support-for-fullcone-nat.patch
          sed -i '30s/1/0/g' package/network/config/firewall4/patches/001-firewall4-add-support-for-fullcone-nat.patch
          sed -i '31s/1/0/g' package/network/config/firewall4/patches/001-firewall4-add-support-for-fullcone-nat.patch

      - name: 更新feeds源
        run: |
          ./scripts/feeds update -a

      - name: 调整插件位置
        run: |
          sed -i 's/system/services/g' feeds/luci/applications/luci-app-ttyd/root/usr/share/luci/menu.d/luci-app-ttyd.json

      - name: 删除部分luci文件
        run: |
          pushd feeds/luci/applications
          rm -rf luci-app-passwall

      - name: 删除部分packages文件
        run: |
          pushd feeds/packages/net
          rm -rf adguardhome
          rm -rf brook
          rm -rf chinadns-ng
          rm -rf dns2socks
          rm -rf dns2tcp
          rm -rf dnsproxy
          rm -rf geoview
          rm -rf hysteria
          rm -rf ipt2socks
          rm -rf microsocks
          rm -rf naiveproxy
          rm -rf pdnsd-alt
          rm -rf shadowsocks-rust
          rm -rf shadowsocksr-libev
          rm -rf simple-obfs
          rm -rf smartdns
          rm -rf ssocks
          rm -rf tcping
          rm -rf trojan
          rm -rf trojan-go
          rm -rf trojan-plus
          rm -rf tuic-client
          rm -rf v2ray-core
          rm -rf v2ray-geodata
          rm -rf v2ray-plugin
          rm -rf xray-core
          rm -rf xray-plugin

      - name: 安装feeds源
        run: |
          ./scripts/feeds install -a

      - name: 构建自定义文件结构
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/symonlee/openwrt-smartdns xipk
          pushd xipk
          rm -rf AdGuardHome
          popd
          git clone https://github.com/xiaorouji/openwrt-passwall luci-app-passwall
          git clone https://github.com/xiaorouji/openwrt-passwall-packages
          pushd luci-app-passwall/luci-app-passwall/root/etc
          rm -rf hotplug.d

      - name: 载入自定义配置
        run: |
          sed -i '8s/1/0/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '9s/chinadns-ng/dnsmasq/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '10s/tcp/udp/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '11s/1.1.1.1/127.0.0.1:5335/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '21s/proxy/disable/2' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '23s/1/0/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '25,26s/1/0/g' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          sed -i '94,106d' package/openwrt-packages/luci-app-passwall/luci-app-passwall/root/usr/share/passwall/0_default_config
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF

          # 编译rpi-4固件:
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r6s=y

          # 编译ext4固件:
          # CONFIG_TARGET_ROOTFS_EXT4FS is not set

          # 设置固件大小:
          CONFIG_TARGET_ROOTFS_PARTSIZE=300

          # DNSMASQ-FULL支持:
          # CONFIG_PACKAGE_dnsmasq is not set
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_dnsmasq_full_ipset=y
          # CONFIG_PACKAGE_ipv6helper is not set
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_ip6tables-nft=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-iprange=y
          CONFIG_PACKAGE_iptables-mod-nat-extra=y
          CONFIG_PACKAGE_iptables-mod-socket=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          CONFIG_PACKAGE_iptables-nft=y
          CONFIG_PACKAGE_xtables-nft=y

          # 文件系统支持:
          # CONFIG_USE_APK is not set
          CONFIG_PACKAGE_block-mount=y
          CONFIG_PACKAGE_kmod-fs-exfat=y
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-vfat=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_kmod-usb-storage-uas=y

          # USB3.0支持:
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y

          # 系统中文支持:
          CONFIG_PACKAGE_default-settings-chn=y

          # 常用LuCI插件选择:
          CONFIG_PACKAGE_luci-app-cpufreq=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-ksmbd=y
          CONFIG_PACKAGE_luci-app-package-manager=y
          CONFIG_PACKAGE_luci-app-passwall=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Geodata=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-ttyd=y

          # 常用软件包:
          CONFIG_PACKAGE_AdGuardHome=y
          CONFIG_PACKAGE_autocore=y
          CONFIG_PACKAGE_btop=y
          CONFIG_PACKAGE_dnsproxy=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_bind-dig=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          # CONFIG_PACKAGE_wpad-basic-mbedtls is not set
          # CONFIG_PACKAGE_wpad-basic-openssl is not set
          # CONFIG_PACKAGE_wpad-basic-wolfssl is not set
          CONFIG_PACKAGE_zoneinfo-asia=y
          
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: 进行固件编译
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: 固件整理
        run: |
          mkdir -p ./artifact/firmware
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*sysupgrade.img.gz" -o -name "sha256sums") ./artifact/firmware/

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware/
